### ISSUE TITLE
[Release v2.019] Qihoo-360 VirusTotal report

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack-windows-installer#1]
Thoughts on what this is picking up @texhex? 1/50 in the red:

`HEUR/QVM06.1.0000.Malware.Gen`

https://www.virustotal.com/en/file/a084365bb213c8dec8b402c60a6191db427696a16a41e08aaa792c5ada5bdf5f/analysis/1461433821/

**Comment by texhex** [comment]
Unfortunately, there is nothing I can do about this. For whatever reason, Qihoo will detect all InnoSetup-based setups I have tried on Virustotal as "Malware.Gen(eric)". I assume this comes from the fact that InnoSetup is also often used for installing Malware. 

As I have written the setup, and can ensure that it's not adware, and given that 54 other AV vendors agree with me on this, this is clearly a *false positive*.

**Comment by chrissimpkins** [comment]
thanks
