### ISSUE TITLE
Add more Hack TTF file names to the list of files that need to be deleted

### ISSUE THREAD

**Issue by texhex** [source-foundry/Hack-windows-installer#14]
[Issue 345 in the Hack repo](https://github.com/source-foundry/Hack/issues/345) shows that having Hack TTF file that have different names, but still report as "Hack" can cause Java based programs to show incorrect glyphs. 

We need to add all TTF files that were used to our kill list so they will be deleted during install in order to avoid these effects.

**Comment by chrissimpkins** [comment]
These are the font paths that I am aware of @texhex:

- Hack-Regular.ttf [otf]
- Hack-Bold.ttf [otf]
- Hack-Italic.ttf [otf]
- Hack-BoldItalic.ttf [otf]
- Hack-Regular-linegap*.ttf [otf]
- Hack-Bold-linegap*.ttf [otf]
- Hack-Italic-linegap*.ttf [otf]
- Hack-BoldItalic-linegap*.ttf [otf]

The *-linegap* paths come from the [font-line tool](https://github.com/source-foundry/font-line) file path rewrite.

**Comment by chrissimpkins** [comment]
Here is the file path format from the documentation for font-line:

> [original filename]-linegap[percent].[ttf|otf]

**Comment by texhex** [comment]
Will be fixed with v1.4.2

**Comment by texhex** [comment]
Updated setup released, closing issue.

**Comment by chrissimpkins** [comment]
:+1:
