### ISSUE TITLE
Installer does not delete font "left overs" from 2.010

### ISSUE THREAD

**Issue by texhex** [source-foundry/Hack-windows-installer#6]
Hack v2.010 has used the font names `Hack Oblique` and `Hack Bold Oblique` instead of `Italic`. The installer should check the registry for these entries and delete them when found.

**Comment by chrissimpkins** [comment]
Note that these could be either otf or ttf builds for the Oblique and Bold Oblique variants.

**Comment by texhex** [comment]
Good point, I really need to check what Windows does when you manually installed an OTF font.

**Comment by texhex** [comment]
The registry font entries `Hack Oblique (TrueType)` and `Hack Bold Oblique (TrueType)` will now be deleted when using the Hack installer (starting with version 1.2.0). 

About OTF: Just when you thought Windows font handling couldn't be more b0rken... OTF fonts are (when using the default Windows method) registered as TrueType! 

For example, when you double-click `Hack-Bold.otf` and select *Install*, Windows will register it as `Hack Bold (TrueType)`, but will point to the .OTF file.

The good thing is, we do not need any special delete command when the user had OTF files installed as we already overwrite any *Hack XXX (TrueType)* entries.

/CC: @chrissimpkins

**Comment by texhex** [comment]
Version 1.2.0 released, issue resolved.

**Comment by chrissimpkins** [comment]
:+1:
