### ISSUE TITLE
Hack entries in Font Subsitutes should also be deleted

### ISSUE THREAD

**Issue by texhex** [source-foundry/Hack-windows-installer#7]
The installer should check ​*HKEY_LOCAL_MACHINE -> SOFTWARE -> Microsoft -> Windows NT -> CurrentVersion  -> FontSubstitutes* and if any Hack *TYPE* (TrueType) entry is found, delete it. 

According to the docs Windows should only check this registry path when a font is requested that is not registered, but we better make sure anyway.

**Comment by texhex** [comment]
Any entry in `FontSubstitutes` that matches the name of a font that Hack Windows Installer is about to install (e.g. `Hack Bold (TrueType)`) will be deleted upon installation starting with version 1.2.0.

**Comment by texhex** [comment]
Version 1.2.0 released, closing issue.

**Comment by chrissimpkins** [comment]
:+1:
