### ISSUE TITLE
The Log-FontData.txt should also note to which files the font registration data points

### ISSUE THREAD

**Issue by texhex** [source-foundry/Hack-windows-installer#8]
See [issue #183](https://github.com/chrissimpkins/Hack/issues/183) in the Hack repository. 

Logging to which file the font registration points should help us to identify what is going wrong on some systems.

**Comment by texhex** [comment]
The next version will first check for the registry values before performing the hash check. If a registry difference is found, this is logged. The entry will look like this:

```
IsSetupFontSameAsInstalledFont(): Hack-BoldItalic.ttf
   Checking for font name in registry: Hack Bold Italic (TrueType)
   Font name found
   Checking for file name in registry. Expected: Hack-BoldItalic.ttf
   File name read: b0rken-Hack-BoldItalic.ttf
   File name in registry is different, installation required
   Found difference for file Hack-BoldItalic.ttf
   Installation required.

**Comment by texhex** [comment]
Version 1.2.0 released which will log the above noted data. Closing issue.

**Comment by chrissimpkins** [comment]
:+1:
